# Generated by Django 6.0 on 2025-12-11 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=255)),
                ('SubjectDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=255)),
                ('CourseDescription', models.TextField()),
                ('CourseDifficulty', models.IntegerField()),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.subject')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseScore', models.CharField(max_length=255)),
                ('CourseFlag', models.CharField(max_length=255)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='accounts.course')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
