# Generated by Django 6.0 on 2025-12-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject_course_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionDescription', models.TextField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.course')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('OptionText', models.TextField()),
                ('CorrectOption', models.BooleanField()),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.question')),
            ],
        ),
    ]
