# Generated by Django 6.0 on 2025-12-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
        ('accounts', '0003_question_option'),
    ]

    operations = [
    ]
