# Generated by Django 6.0 on 2025-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0002_passwordresettoken_0003_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
