# Generated by Django 6.0 on 2025-12-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0002_passwordresettoken_0003_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
