# Generated by Django 6.0 on 2025-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='CompletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
