# Generated by Django 6.0 on 2025-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subjectbookmark'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subjectbookmark',
            new_name='accounts_su_user_id_1f394d_idx',
            old_name='accounts_su_user_id_5c74ee_idx',
        ),
        migrations.AddField(
            model_name='subject',
            name='icon_svg_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
