# Generated by Django 6.0 on 2025-12-22 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_licensekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='expires_at',
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('name_cn', models.CharField(blank=True, default='', max_length=150)),
                ('subject_en', models.CharField(blank=True, default='', max_length=255)),
                ('subject_cn', models.CharField(blank=True, default='', max_length=255)),
                ('course_titles', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
