# Generated by Django 6.0 on 2025-12-22 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_licensekey_expires_at_usercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usercertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('user', 'subject'), name='unique_user_subject_certificate'),
        ),
    ]
